baseURL = 'https://shennmue.github.io/blog/'
title = "shenblog"
theme = "hugo-blog-awesome"
languageCode = "en-US"
defaultContentLanguage = "en"
contentDir = "content/en" # Indique à Hugo que tes articles sont dans ce dossier

[markup.goldmark.renderer]
  unsafe = true # Indispensable pour que tes balises <img> fonctionnent !

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 10

  [[menu.main]]
    name = 'Categories'
    url = '/categories/'
    weight = 40

  [[menu.main]]
    name = 'All posts'
    url = '/posts/'
    weight = 20

  [[menu.main]]
    name = 'About me'
    url = '/posts/whoami'
    weight = 40


[params]
  sitename = "shenblog"
  defaultColor = "auto"
  mainSections = ['posts']
  dateFormat = "2 January 2006"

  [params.author]
    avatar = "avatar.jpg" 
    intro = "Welcome to shenblog"
    name = "Ali Hammoudi"
    description = "In this blog, you will find some of my creations and projects I've worked on, enjoy!"

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/shennmue"

[[params.socialIcons]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/ali-hammoudi-rouen/"